### ISSUE TITLE
Problem in building image 

### ISSUE THREAD

**Issue by androna-xm** [joe-elliott/tempo-otel-example#5]
I ran the command `./build.sh ` but i got the following output and so the tracing-example image was not built. 

#go.opentelemetry.io/otel/sdk/trace
../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.16.0/trace/span.go:71:2: duplicate method IsRecording
../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.16.0/trace/span.go:71:2: duplicate method SpanContext
../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.16.0/trace/span.go:71:2: duplicate method Tracer
note: module requires Go 1.14
Sending build context to Docker daemon  481.8kB
Step 1/6 : FROM alpine:3.13
 ---> 6dbb9cc54074
Step 2/6 : RUN addgroup -g 1000 app &&     adduser -u 1000 -h /app -G app -S app
 ---> Using cache
 ---> 65ab7c11ad01
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> 2ce8f46c7aaa
Step 4/6 : USER app
 ---> Using cache
 ---> 606e0fb3568b
Step 5/6 : COPY ./app .
COPY failed: file not found in build context or excluded by .dockerignore: stat app: file does not exist
rm: cannot remove 'app': No such file or directory

**Comment by joe-elliott** [comment]
Unsure. I just ran `./build.sh` w/o issue. That's also a really weird error. It suggests that some methods are defined twice in the same module.

Can you double check that the imported otel sdk looks correct?

**Comment by androna-xm** [comment]
I think the duplicate messages are because i ran the command  twice. At first the only error was that 'app' file was not found so step 5/6 failed. I just cloned the repo , i didn't change anything before running the build command.

**Comment by joe-elliott** [comment]
Perhaps pull the build command out of the script and experiment with it on its own? I have wiped and recloned the repo and am not having issues.

**Comment by androna-xm** [comment]
I just saw that 

> note: module requires Go 1.14

 in the output. 
So i will try to update my go version too.

**Comment by androna-xm** [comment]
It looks like the go version was the problem! Thank you !
