### ISSUE TITLE
Question: why not need run otel-collector?

### ISSUE THREAD

**Issue by Leadrive** [joe-elliott/tempo-otel-example#9]
Hi, I try to run this project, it work ok.
in the main.go
````golang
	driver := otlpgrpc.NewDriver(
		otlpgrpc.WithInsecure(),
		otlpgrpc.WithEndpoint("tempo:55680"),
		otlpgrpc.WithDialOption(grpc.WithBlock()), // useful for testing
	)
````
But I can not find any 55680 port application, why not need run otel-collector?

Another question, If I run app(tracing-example) in metal deployment(command line mode, not docker container), how to set EndPoint?
otlpgrpc.WithEndpoint("????"),

Thank you very much.

**Comment by joe-elliott** [comment]
The application is speaking to Tempo directly. If you'd like to submit a PR that also uses the collector I'd merge it. I just didn't need it so I didn't bother.

`WithEndpoint()` just needs to correctly address Tempo. So however Tempo is addressable from the application. If it's on the same host then "localhost:55680" should work.

**Comment by Leadrive** [comment]
thank you.
